export const JUDGE0_LANGUAGE_IDS = {
  JAVASCRIPT: 63,
  PYTHON: 71,
  JAVA: 62,
  CPP: 54,
  C: 50,
} as const;

export const JUDGE0_STATUS = {
  IN_QUEUE: 1,
  PROCESSING: 2,
  ACCEPTED: 3,
  WRONG_ANSWER: 4,
  TIME_LIMIT_EXCEEDED: 5,
  COMPILATION_ERROR: 6,
  RUNTIME_ERROR: 7,
  INTERNAL_ERROR: 8,
  EXEC_FORMAT_ERROR: 9,
  SYSTEM_ERROR: 10,
  MEMORY_LIMIT_EXCEEDED: 11,
} as const;
