export const MESSAGES = {
  REGISTER_SUCCESS: 'Register successfully!',
  LOGIN_SUCCESS: 'Login successfully!',
  REFRESH_TOKEN_SUCCESS: 'Refresh token successfully!',
  LOGOUT_SUCCESS: 'Logout successfully!',
  VERIFY_EMAIL_SUCCESS: 'Verify email successfully!',
  FORGOT_PASSWORD_SUCCESS: 'Send reset password email successfully!',
  RESET_PASSWORD_SUCCESS: 'Reset password successfully!',
  INVALID_EMAIL_OR_PASSWORD: 'Invalid email or password!',
  USER_ALREADY_EXISTS: 'User already exists!',
  TOKEN_REVOKED: 'Token revoked!',
  GET_ME_SUCCESS: 'Get me successfully!',
  USER_NOT_FOUND: 'User not found!',
  USER_ALREADY_VERIFIED: 'User already verified!',
  USER_NOT_VERIFIED: 'User not verified!',
} as const;
