export const MESSAGES = {
  REGISTER_SUCCESS: 'Register successfully!',
  LOGIN_SUCCESS: 'Login successfully!',
  REFRESH_TOKEN_SUCCESS: 'Refresh token successfully!',
  LOGOUT_SUCCESS: 'Logout successfully!',
  VERIFY_EMAIL_SUCCESS: 'Verify email successfully!',
  FORGOT_PASSWORD_SUCCESS: 'Send reset password email successfully!',
  RESET_PASSWORD_SUCCESS: 'Reset password successfully!',
  INVALID_EMAIL_OR_PASSWORD: 'Invalid email or password!',
  USER_ALREADY_EXISTS: 'User already exists!',
  TOKEN_REVOKED: 'Token revoked!',
  GET_ME_SUCCESS: 'Get me successfully!',
  USER_NOT_FOUND: 'User not found!',
  USER_ALREADY_VERIFIED: 'User already verified!',
  USER_NOT_VERIFIED: 'User not verified!',
  CREATE_PROBLEM_SUCCESS: 'Create problem successfully!',
  PROBLEM_ALREADY_EXISTS: 'Problem already exists!',
  PROBLEM_NOT_FOUND: 'Problem not found!',
  GET_PROBLEM_SUCCESS: 'Get problem successfully!',
  GET_ALL_PROBLEMS_SUCCESS: 'Get all problems successfully!',
  CODE_SUBMITTED_SUCCESS: 'Code submitted successfully!',
  CODE_RUN_SUCCESS: 'Code run successfully!',
  GET_SUBMISSIONS_SUCCESS: 'Get submissions successfully!',
  GET_SUBMISSION_SUCCESS: 'Get submission successfully!',
  SUBMISSION_NOT_FOUND: 'Submission not found!',
  SUBMISSION_NOT_ALLOWED: 'Submission not allowed!',
} as const;
